[package]
name = "nom-miette"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
# miette = "7.2.0"
miette = { git = "https://github.com/TheLostLambda/miette", branch = "tll-fork" }
nom = "7.0.0"
thiserror = "1.0.59"

[lints]
workspace = true
