[package]
name = "nom-miette"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
# miette = "7.2.0"
miette = { git = "https://github.com/TheLostLambda/miette", branch = "tll-fork" }
nom = "7.1.3"
thiserror = "2.0.12"

[lints]
workspace = true
