[package]
name = "nom-miette"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
getrandom = { version = "0.2.14", features = ["js"] }
# miette = "7.2.0"
miette = { git = "https://github.com/TheLostLambda/miette" }
nom = "7.1.3"
thiserror = "1.0.59"

[lints]
workspace = true
