[package]
name = "dimer-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
muropeptide = { path = "../muropeptide" }
polars-core = "0.43.1"
polars-lazy = "0.43.1"
polychem = { path = "../polychem" }

[lints]
workspace = true
