[package]
name = "dimer-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
muropeptide = { path = "../muropeptide" }
polars-core = "0.46.0"
polars-lazy = "0.46.0"
polychem = { path = "../polychem" }

[lints]
workspace = true
