[package]
name = "smithereens"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
derive_more = "2.0.1"
itertools = "0.14.0"
polychem = { path = "../polychem" }

[lints]
workspace = true
