[package]
name = "smithereens"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
derive_more = "1.0.0"
itertools = "0.13.0"
polychem = { path = "../polychem" }

[lints]
workspace = true
