[package]
name = "database-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
muropeptide = { path = "../muropeptide" }
polychem = { path = "../polychem" }
nom-miette = { path = "../nom-miette" }

[lints]
workspace = true
